### PR TITLE
Fix#9323: Can't modify profiles created via "Save as profile"

### LINKED ISSUE #9323: Can't modify profiles created via "Save as profile"
**Describe the problem**:

You can't save profiles if the profile is created via  "Save as profile"  from an active tab that was just a one-off ssh session. 

To be specific,  the profile is saved the first time when you right click the tab and Save as profile, but if you then go into settings to make modifications to the new profile you are unable to save the changes,  clicking the save button does nothing and the profile dialog stays open.

### PR DESCRIPTION
**Pull request by Clem-Fern**
Hey @Eugeny 

This PR aims to fix #9323. The issue is caused by `tab.profile.options` being a reference to a `ConfigProxy` instance in some case.

```
error_handler.ts:45 ERROR TypeError: Cannot delete property 'hmac' of [object Object]
    at ConfigProxy.__setValue (/opt/Tabby/resources/builtin-plugins/tabby-core/dist/index.js:20266:29)
    at ConfigProxy.set [as hmac] (/opt/Tabby/resources/builtin-plugins/tabby-core/dist/index.js:20241:30)
    at SSHProfileSettingsComponent.save (/opt/Tabby/resources/builtin-plugins/tabby-ssh/dist/index.js:7553:48)
    at EditProfileModalComponent.save (/opt/Tabby/resources/builtin-plugins/tabby-settings/dist/index.js:7167:139)
    at EditProfileModalComponent_Template_button_click_37_listener (template.html:70:44)
    at executeListenerWithErrorHandling (listener.ts:224:12)
    at wrapListenerIn_markDirtyAndPreventDefault (listener.ts:261:18)
    at HTMLButtonElement.<anonymous> (dom_renderer.ts:76:34)
    at _ZoneDelegate.invokeTask (zone.js:402:31)
    at Object.onInvokeTask (ng_zone.ts:408:29)
    at _ZoneDelegate.invokeTask (zone.js:401:60)
    at Zone.runTask (zone.js:171:47)
    at ZoneTask.invokeTask [as invoke] (zone.js:483:34)
    at invokeTask (zone.js:1631:18)
    at globalCallback (zone.js:1662:29)
    at HTMLButtonElement.globalZoneAwareCallback (zone.js:1695:16)
    at HTMLButtonElement.sentryWrapped (helpers.ts:87:17)
```

With this fix, options real instance is retrieved before cloning it. Newly saved profile is then cleaned up from any remaining default options before being added into profiles.

Fix #9323

### CODE REVIEW

**Comment by Eugeny** [comment]
I don't quite like this solution because it exposes a lot of ConfigProxy guts where they shouldn't be visible.

The actual issue is that [here](https://github.com/Eugeny/tabby/pull/10010/files#diff-15649e29d01603e88cbdffb1b97523985ed1b3f5cf7a2611c9126026ae5099ecL184) the `...` operator was supposed to turn a ConfigProxy into a "normal" object, but it doesn't do that recursively.

Using `clone-deep` should fix it directly.

**Comment by Clem-Fern** [comment]
> I don't quite like this solution because it exposes a lot of ConfigProxy guts where they shouldn't be visible.
>
> Using `clone-deep` should fix it directly.

Yeah I definitely agree. I tried clone-deep before this but sadly it doesn't do the job.

```typescript
const options = { ...deepClone(tab.profile.options) }
console.log(options)
```
```
error_handler.ts:45 ERROR Error: Uncaught (in promise): TypeError: Cannot delete property 'hmac' of [object Object]
TypeError: Cannot delete property 'hmac' of [object Object]
    at ConfigProxy.__setValue (config.service.ts:88:29)
    at ConfigProxy.__cleanup (config.service.ts:101:26)
    at ConfigProxy.__cleanup (config.service.ts:98:31)
    at ConfigProxy.__cleanup (config.service.ts:98:31)
    at SaveAsProfileContextMenu.<anonymous> (tabContextMenu.ts:204:80)
    at Generator.next (<anonymous>)
    at fulfilled (tslib.es6.js:73:58)
    at _ZoneDelegate.invoke (zone.js:368:26)
    at Object.onInvoke (ng_zone.ts:423:29)
    at _ZoneDelegate.invoke (zone.js:367:52)
    at resolvePromise (zone.js:1193:31)
    at zone.js:1100:17
    at zone.js:1116:33
    at fulfilled (tslib.es6.js:73:86)
    at _ZoneDelegate.invoke (zone.js:368:26)
    at Object.onInvoke (ng_zone.ts:423:29)
    at _ZoneDelegate.invoke (zone.js:367:52)
    at Zone.run (zone.js:127:43)
``

**Comment by Clem-Fern** [comment]
Well that's weird. Do you save a restored tab or a newly opened tab ?

**Comment by Eugeny** [comment]
A new tab. I've also checked that its tab.profile.options is actually a Config proxy before getting cloned

**Comment by Eugeny** [comment]
You're right - I must have screwed up while testing it somewhere - but finally fixed in 21aedb6045d710530705307c34b618cdca1a0d84

**Pull request closed without merging**
