### PR TITLE
Fix Windows Builds

### PR DESCRIPTION
**Pull request by Jai-JAP**
Fixes Windows arm64 builds and probably doesnt break windows x64 builds
Artifacts [here](https://github.com/Jai-JAP/tabby/actions/runs/2102139058)

### CODE REVIEW

**Comment by Jai-JAP** [comment]
To be tested on Windows machines

**Comment by Eugeny** [comment]
x64 build is still broken - shouldn't the `$ARCH` actually be `x64` instead of `x86_64` here? That's what `process.arch` is on x64 Windows.

**Comment by Jai-JAP** [comment]
https://github.com/Jai-JAP/tabby/actions/runs/2141322690
@Eugeny can you test these new build artifacts

**Comment by Jai-JAP** [comment]
Also have you tested theaxOS x86_64 builds as theyay also have the same issue

**Comment by Jai-JAP** [comment]
https://github.com/Jai-JAP/tabby/actions/runs/2141391555

Here are the latest builds

**Comment by Eugeny** [comment]
31f549f5bb8d20c331163a2f24b38fe6db7e7b84 works on Windows x64

**Comment by Eugeny** [comment]
579b60236b04156d3e42f6c16f5d5d334714022b broke it again, the new condition is equivalent to

```
process.env.ARCH = (process.env.ARCH || (process.arch === 'arm')) ? 'armv7l' : process.arch``` and always returns `armv7l`

**Comment by Eugeny** [comment]
Shouldn't it be just `process.env.ARCH = (process.env.ARCH || process.arch) === 'arm' ? 'armv7l' : process.arch` ?

**Comment by Jai-JAP** [comment]
> Shouldn't it be just `process.env.ARCH = (process.env.ARCH || process.arch) === 'arm' ? 'armv7l' : process.arch` ?

I will commit this and again can you try the build as my windows system is broken

**Comment by Jai-JAP** [comment]
Also fixed the same in build-linux.js

**Comment by Jai-JAP** [comment]
Aftifacts
[Fix build-native.js]( https://github.com/Jai-JAP/tabby/actions/runs/2143817136)
[Fix build-linux.js](https://github.com/Jai-JAP/tabby/actions/runs/2143822445)

**Comment by Jai-JAP** [comment]
@Eugeny Have you tested the Mac OS x86_64 builds as they may also have the same issue

**Comment by Jai-JAP** [comment]
Windows x64 build is tested working on my friend's PC
Windows arm64 has to be tested however

**Comment by Eugeny** [comment]
macOS x64 confirmed working

**Comment by Jai-JAP** [comment]
Ok then...
Ready to merge

**Pull request merged**
