### PR TITLE
Fix#8915: selector prevent edit selection on prolonged keydown

### LINKED ISSUE #8915: Funny but annoying Backspace issue in Profiles & connections
Hey, Eugeny. 
My Tabby version is 1.0.196 (the last actual version from apt repository).
In Profile & connection popup you can start typing a name of the profile to quickly connect to it. But if you made a mistake and want to delete everything, you hold the Backspace key expecting it to stop at the end of the line, when all characters are deleted. But it's not.
If you press or hold Backspace key It doesn't stop and instead somehow pastes a name of a recent profile and continues to delete it, until reaches the last characted, and then it happens again infinitely.

Here's the video with keypresses indicator at the bottom for clearity.

https://github.com/Eugeny/tabby/assets/13274062/1f65fa70-79d3-4663-8ebe-8cedfa56efcd

### PR DESCRIPTION
**Pull request by Clem-Fern**
Hey @Eugeny, I hpe you're great !

As discuss in #8915, pressing Backspace in selector without releasing the key immediately edit the selected item. It can be a bit unpractical. This PR aims to fix this problem by preventing item edition if backspace keyup event hasn't been fired before.

Feel free to aske if any changes needed :)

Fix #8915

### CODE REVIEW

**Comment by Eugeny** [comment]
Thank you!

**Comment by konstantin83** [comment]
I'm still not so good in github, unfotunately ( Can you please tell if this fix is already in release or in alpha? I mean, can I already somehow download a version that contains it?

**Comment by Clem-Fern** [comment]
Hey @konstantin83,

You can download the latest night build here :
https://nightly.link/Eugeny/tabby/workflows/build/master

**Comment by konstantin83** [comment]
@Clem-Fern thank you. I tried to download the latest 1.0.201, but there is no linux release in it.
So I downloaded 1.0.200, and the bug is still there.
Sorry for bothering you, but maybe I'm doing something wrong?

**Comment by Eugeny** [comment]
@konstantin83 Linux binaries have failed to upload for the v201 release but I've added them manually now

**Comment by konstantin83** [comment]
Dear @Clem-Fern and @Eugeny thank you for you help! It's ok now!
Ans also I didn't even know what backspace was for in Select Profile popup. Now I know )

**Pull request merged**
