### PR TITLE
 fix #4684 - removing profile's hotkeys on profile delete

### LINKED ISSUE #4684: (Bug) Deleting a profile via the "Profiles" tab doesn't remove it's hotkeys from config.yaml
Version: 1.0.158
Platform: Windows x64 10.0.19043

After deleting a profile via "Profiles" tab, it's hotkeys for "New tab" still remain in the config.yaml file. This can sometimes lead to binds not working.

Create a profile and assign a shortcut for "New tab: <profile>". Delete this profile and create a new one.  To the new profile, assign the same key combination for "New tab: <profile>".

The old profile is removed from the "profiles" list, but not from "hotkeys.profile".

This is what that looks like:
```
profile:
    local:git-bash: []
    local:custom:test-1:e574684e-0982-4fcc-9cc8-8665307c63e2:
      - - Ctrl-Shift-]
    local:custom:test-2:3dc1c968-8610-4686-a1a3-f2310078a1b6:
      - - Ctrl-Shift-]
```
Where "test-1" is the profile that was created and then deleted, and "test-2" the profile that was created afterwards.
As a result, the key combination doesn't do anything when pressed.

I understand it can be manually fixed by deleting it from the config file, but I wanted to point it out anyways.

### PR DESCRIPTION
**Pull request by Clem-Fern**
Hi @Eugeny,

This PR aims to fix the issue Eugeny/tabby#4684 by removing profile's hotkeys if some are present when the profile is deleted.
I moved the function `getProfileHotkeyName` in the abstract class HotkeyProvider. In that way, the function can be used through the api.

If I understood properly, using `delete` operator to dynamically remove keys from an object is not recommended. So feel free to ask if changes needed or if you want me to find a better way to delete hotkeys.

### CODE REVIEW

**Comment by Eugeny** [comment]
Have you checked that it works? `config.store` is a proxy object with dynamic properties (defined in https://github.com/Eugeny/tabby/blob/master/tabby-core/src/services/config.service.ts#L32-L59) and `delete` likely won't delete the underlying value.  

I'd also rather export `AppHotkeyProvider` from `tabby-core` than add unrelated functionality to the base class

**Comment by Clem-Fern** [comment]
> Have you checked that it works? `config.store` is a proxy object with dynamic properties (defined in https://github.com/Eugeny/tabby/blob/master/tabby-core/src/services/config.service.ts#L32-L59) and `delete` likely won't delete the underlying value.
> 
> I'd also rather export `AppHotkeyProvider` from `tabby-core` than add unrelated functionality to the base class
> 
> >  GitHub**[tabby/config.service.ts at master · Eugeny/tabby](https://github.com/Eugeny/tabby)**A terminal for a more modern age. Contribute to Eugeny/tabby development by creating an account on GitHub.

Yup, it works. It seems that using `delete` call the `__setValue`method defined into the proxy to set the `profile` object without the deleted property. But i can see now why it is ambiguous.
Does deleting the property as below could be more appropriate ?
```
if (this.config.store.hotkeys.profile.hasOwnProperty(profileHotkeyName)) {
       const profileHotkeys = deepClone(this.config.store.hotkeys.profile)
       // eslint-disable-next-line @typescript-eslint/no-dynamic-delete
       delete profileHotkeys[profileHotkeyName]
       this.config.store.hotkeys.profile = profileHotkeys
}
```

**Comment by Eugeny** [comment]
Got it, thanks! If you could just move `getProfileHotkeyName` then we're good to go.

**Comment by Clem-Fern** [comment]
Yeah sure, no problem.
I'm opening a new pull request with the adequate commits :)

**Pull request closed without merging**
