### PR TITLE
Config of different configProviders combination merge together

### PR DESCRIPTION
**Pull request by wljince007**
Fix merge code error, different providers' configs should be merged instead of replaced（修复合并代码错误,不同providers的config应该是合并不应该是替换）

### CODE REVIEW

**Comment by Eugeny** [comment]
Why?

**Comment by wljince007** [comment]
From a semantic perspective, the configurations written by different configuration providers should also be merged, rather than replacing the configurations of plugins loaded later with those of plugins in the previous architecture.(看语义，不同的配置提供者写的配置也应该是合并，不应该是后面加载的插件的配置的替换前面架构的插件的配置。)

For example i write a plugin tabby-sftp-tab, the plugin want add profiles to defaults, but the merge  always make the default profiles to [].

**Comment by wljince007** [comment]
export const configMerge = (a, b) => deepmerge(a, b, { arrayMerge: (_d, s) => s })     //Replace merge

export const configMergeyByDefault = (a, b) => deepmerge(a, b)      //Or merge


    mergeDefaults (): unknown {
        const providers = this.configProviders
        return providers.map(provider => {
            let defaults = provider.platformDefaults[this.hostApp.configPlatform] ?? {}
            defaults = configMerge(
                defaults,
                provider.platformDefaults[this.hostApp.platform] ?? {},
            )
            if (provider.defaults) {
                defaults = configMerge(provider.defaults, defaults)
            }
            return defaults
        }).reduce(configMergeyByDefault)   //config of different configProviders should OR Merge

**Comment by wljince007** [comment]
@Eugeny  Is it right?

**Comment by wljince007** [comment]
@Eugeny  Is my understanding correct? Should the configuration content of different configProvider be merged together?

**Comment by Eugeny** [comment]
Sorry for the delay - you're right :) Pls just fix the typo in the name and I'll merge :v:

**Comment by wljince007** [comment]
@Eugeny   Thank you for your guidance. The name of the request has been modified

**Comment by Eugeny** [comment]
Sorry, I meant the variable name ("mergey" should be "merge")

**Comment by Eugeny** [comment]
@all-contributors please add @wljince007 for code

**Comment by wljince007** [comment]
Sorry, the variable name was written incorrectly and has been modified. Thank you again for your patient guidance.

**Pull request merged**
