### PR TITLE
feat: tab context menu 'Restart'

### PR DESCRIPTION
**Pull request by Qiming-Liu**
For issue https://github.com/Eugeny/tabby/issues/6653#issue-1280295196

image

### CODE REVIEW

**Comment by Eugeny** [comment]
For this option, I would prefer a hotkey instead of a menu entry - as it's rarely necessary for local shells, and remote tabs already have their own dedicated restart button.

**Comment by Qiming-Liu** [comment]
> For this option, I would prefer a hotkey instead of a menu entry - as it's rarely necessary for local shells, and remote tabs already have their own dedicated restart button.

Agree, I’ll try to make a hotkey instead of this tomorrow. Thanks for your reply!

**Comment by Qiming-Liu** [comment]
image


Tested on windows works fine.
No default hotkey value.

Please let me know if this is ok.

**Comment by Eugeny** [comment]
This is great, thanks!

**Pull request merged**
