### PR TITLE
Translated, linked & polished

### PR DESCRIPTION
**Pull request by MagicLike**
Hey there!
I translated the README into german, linked the READMEs together - except for the Korean README (There is no "This README is also available in" in Korean), Changed "Inglese" to "English" in the Italian README, so that it is generalized, because otherwise everywhere the languages are called in the associated language. I Also removed the Link to the Chinese translation in the Chinese translation itself and lastly added flags to all Translations (exept for the Korean, reason see above) for a more polished and clean look.

### CODE REVIEW

**Comment by Eugeny** [comment]
Very nice! Could you please also add it to the `.all-contributorsrc`?

**Comment by MagicLike** [comment]
Done 👍

**Comment by MagicLike** [comment]
@Eugeny Would it be possible to add me to the list of contributors?

**Comment by Eugeny** [comment]
Absolutely! Forgot to do it right away 🤦   @allcontributors please add @MagicLike for docs

**Comment by MagicLike** [comment]
No Problem, Thanks!

**Pull request merged**
