### PR TITLE
Optimize the profile experience on Windows

### PR DESCRIPTION
**Pull request by LiangchengJ**
## After

***
***
- [Switch to more classic linux icon](https://github.com/Eugeny/tabby/commit/ec22c00ba563a00928f174f3ff44d56fb497f1d5)

- [Use linux icon by default when no WSL profile icon is found](https://github.com/Eugeny/tabby/commit/a5fb7262063170fd11a1015a15e094d3ff06c198)
- [Different versions of vs profile use different icon to differentiate](https://github.com/Eugeny/tabby/commit/fa2bbe39c4db6e55ed79c733d86eb76821a1e6b4)
- [Fix the problem that the `Developer Prompt for VS 2022` profile could not be loaded](https://github.com/Eugeny/tabby/commit/7cddcee9518ea6bb53d1042fce138660295f72bd) 
- [Update official icon for git bash profile](https://github.com/Eugeny/tabby/commit/0aa7e53a783570ac57f3a1e46210368c227dc643)

- [Change name `Git-Bash` to `Git Bash`](https://github.com/Eugeny/tabby/commit/272918bff66c2ccebd107d8129469b7d56049c80)
- [Update official icon for powershell profiles](https://github.com/Eugeny/tabby/commit/b154d87865520dd6cd7b10eb9dfb7aa470c8aba9)

- [Add icon for `Ubuntu-22.04` profile](https://github.com/Eugeny/tabby/commit/6dc14e0fd58f983c2dabd8c3fd5accd6b917dd0b)
- [Add icon for `AlmaLinux-8` profile](https://github.com/Eugeny/tabby/commit/9f4c12ba96c9b1b02935a189751619d4cc21dacd)
- [Add icon for `openEuler` profile](https://github.com/Eugeny/tabby/commit/175016bb1a2c0b90e0e8d44966e88099fc9b4aea)
- [Add icon for oracle wsl profiles](https://github.com/Eugeny/tabby/commit/e537b61edd4cebe19cc129a8f63d3ad47bbcf274)
- [Update official icon for kali profile](https://github.com/Eugeny/tabby/commit/7e0b9ecb568d2a90db2d5fdb697cdcc850930faa)

### CODE REVIEW

**Comment by LiangchengJ** [comment]
@Eugeny Hey, boy.

**Comment by Eugeny** [comment]
@allcontributors please add @LiangchengJ for code

image

👁️ 👁️

**Comment by mloskot** [comment]
I have asked about this fix in thread https://github.com/Eugeny/tabby/discussions/7175 as I'm not seeing the profiles in 1.0.183

**Comment by LiangchengJ** [comment]
> I have asked about this fix in thread https://github.com/Eugeny/tabby/discussions/7175 as I'm not seeing the profiles in 1.0.183
> 
> <blockquote><div> GitHub</div><div><strong><a href="https://github.com/Eugeny/tabby/discussions/7175">Developer Prompt for Visual Studio in 1.0.183 · Discussion #7175 · Eugeny/tabby</a></strong></div><div>I have installed Tabby 1.0.183 on Windows 10 and, after reading about the Added automatic Developer Tools for Visual Studio profiles on Windows, I was hoping it will auto-configure itself with the ...</div></blockquote>

Do you have Build Tools for Visual Studio or Visual Studio installed in Windows?

**Pull request merged**
