### PR TITLE
Added README.pl-PL.md and <a> anchors with Polish language availability

### PR DESCRIPTION
**Pull request by botprzemek**
### Polish markdown addition 🇵🇱

This Pull Request adds Polish language translation to markdown 🇵🇱. File was fully written by a Polish native (me) without any translators or AI.

Files added:
 - [README.pl-PL.md](https://github.com/botprzemek/tabby-polish/blob/master/README.pl-PL.md) - project's markdown translated to Polish
 - Anchors inside every other language

Good luck, botprzemek

### CODE REVIEW

**Comment by Eugeny** [comment]
Thank you!

**Comment by Eugeny** [comment]
@all-contributors add @botprzemek for docs

**Comment by Eugeny** [comment]
Feel free to make a PR :v:

**Comment by botprzemek** [comment]
Dzięki za poprawkę @BigPebble123 :trollface:

**Pull request merged**
