### PR TITLE
Bump Electron to 32 as 29 is EOL

### PR DESCRIPTION
**Pull request by geodic**
The title says it...

### CODE REVIEW

**Comment by geodic** [comment]
It looks like the tests are failing as the image they are running on uses g++ 9 when the minimum required version is g++ 10. Updating the Ubuntu version should fix it...

**Comment by geodic** [comment]
@Eugeny, could you please take a look at this PR as soon as possible? Another PR is waiting on it. Thanks so much!

**Comment by geodic** [comment]
The build is successful! :confetti_ball: :confetti_ball:

**Comment by Eugeny** [comment]
LGTM now, thanks!

**Comment by Eugeny** [comment]
@all-contributors add @geodic for code

**Comment by geodic** [comment]
TSYM :)

**Comment by geodic** [comment]
@Eugeny, sorry for pinging you again, but I just wanted to ask if it's possible to release a new version so I can get the Nix PR merged. Thanks again!

**Comment by Eugeny** [comment]
Currently not, v216 has introduced some major issues with SSH and I need to find a solution before pushing another update.

**Pull request merged**
