### PR TITLE
Fix builds

### LINKED ISSUE #9235: Issue after update on ubuntu 22.04
Nov 15 13:26:56    ubuntu systemd[2367]: Started Application launched by gnome-shell.
Nov 15 13:26:57    ubuntu tabby.desktop[8609]: innerError Error: Cannot find module '../build/Debug/pty.node'
Nov 15 13:26:57    ubuntu tabby.desktop[8609]: Require stack:
Nov 15 13:26:57    ubuntu tabby.desktop[8609]: - /opt/Tabby/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js
Nov 15 13:26:57    ubuntu tabby.desktop[8609]: - /opt/Tabby/resources/app.asar/node_modules/node-pty/lib/index.js
Nov 15 13:26:57    ubuntu tabby.desktop[8609]: - /opt/Tabby/resources/app.asar/dist/main.js
Nov 15 13:26:57    ubuntu tabby.desktop[8609]: -
Nov 15 13:26:57    ubuntu tabby.desktop[8609]:     at Module._resolveFilename (node:internal/modules/cjs/loader:1082:15)
Nov 15 13:26:57    ubuntu tabby.desktop[8609]:     at Function.n._resolveFilename (node:electron/js2c/browser_init:2:117760)
Nov 15 13:26:57    ubuntu tabby.desktop[8609]:     at Module._load (node:internal/modules/cjs/loader:927:27)
Nov 15 13:26:57    ubuntu tabby.desktop[8609]:     at Function.f._load (node:electron/js2c/asar_bundle:2:13377)
Nov 15 13:26:57    ubuntu tabby.desktop[8609]:     at Module.require (node:internal/modules/cjs/loader:1148:19)
Nov 15 13:26:57    ubuntu tabby.desktop[8609]:     at require (/opt/Tabby/resources/app.asar/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
Nov 15 13:26:57    ubuntu tabby.desktop[8609]:     at Object.<anonymous> (/opt/Tabby/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js:34:15)
Nov 15 13:26:57    ubuntu tabby.desktop[8609]:     at Module._compile (/opt/Tabby/resources/app.asar/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
Nov 15 13:26:57    ubuntu tabby.desktop[8609]:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1324:10)
Nov 15 13:26:57    ubuntu tabby.desktop[8609]:     at Module.load (node:internal/modules/cjs/loader:1124:32) {
Nov 15 13:26:57    ubuntu tabby.desktop[8609]:   code: 'MODULE_NOT_FOUND',
Nov 15 13:26:57    ubuntu tabby.desktop[8609]:   requireStack: [
Nov 15 13:26:57    ubuntu tabby.desktop[8609]:     '/opt/Tabby/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js',
Nov 15 13:26:57    ubuntu tabby.desktop[8609]:     '/opt/Tabby/resources/app.asar/node_modules/node-pty/lib/index.js',
Nov 15 13:26:57    ubuntu tabby.desktop[8609]:     '/opt/Tabby/resources/app.asar/dist/main.js',
Nov 15 13:26:57    ubuntu tabby.desktop[8609]:     undefined
Nov 15 13:26:57    ubuntu tabby.desktop[8609]:   ]
Nov 15 13:26:57    ubuntu tabby.desktop[8609]: }

### LINKED ISSUE #9242: Tabby execute failed
Version: 204
Platform: Manjora Linux

LOG:
innerError Error: Cannot find module '../build/Debug/pty.node'
Require stack:
- /opt/Tabby/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js
- /opt/Tabby/resources/app.asar/node_modules/node-pty/lib/index.js
- /opt/Tabby/resources/app.asar/dist/main.js
- 
    at Module._resolveFilename (node:internal/modules/cjs/loader:1082:15)
    at Function.n._resolveFilename (node:electron/js2c/browser_init:2:117760)
    at Module._load (node:internal/modules/cjs/loader:927:27)
    at Function.f._load (node:electron/js2c/asar_bundle:2:13377)
    at Module.require (node:internal/modules/cjs/loader:1148:19)
    at require (/opt/Tabby/resources/app.asar/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/opt/Tabby/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js:34:15)
    at Module._compile (/opt/Tabby/resources/app.asar/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1324:10)
    at Module.load (node:internal/modules/cjs/loader:1124:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/opt/Tabby/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js',
    '/opt/Tabby/resources/app.asar/node_modules/node-pty/lib/index.js',
    '/opt/Tabby/resources/app.asar/dist/main.js',
    undefined
  ]
}
MESA-INTEL: warning: Haswell Vulkan support is incomplete

### LINKED ISSUE #9245: Failed to execute from Ubuntu 22.04
**Describe the problem**:
After update from Alpha 201 to Alpha 204, tabby cannot be execute from terminal & deskop.

**To Reproduce**:
[Steps to reproduce the behavior]

**Output**
```
OS: Ubuntu 22.04.3 LTS
```

```
user@ubuntu-pc:~$ tabby
innerError Error: Cannot find module '../build/Debug/pty.node'
Require stack:
- /opt/Tabby/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js
- /opt/Tabby/resources/app.asar/node_modules/node-pty/lib/index.js
- /opt/Tabby/resources/app.asar/dist/main.js
- 
    at Module._resolveFilename (node:internal/modules/cjs/loader:1082:15)
    at Function.n._resolveFilename (node:electron/js2c/browser_init:2:117760)
    at Module._load (node:internal/modules/cjs/loader:927:27)
    at Function.f._load (node:electron/js2c/asar_bundle:2:13377)
    at Module.require (node:internal/modules/cjs/loader:1148:19)
    at require (/opt/Tabby/resources/app.asar/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/opt/Tabby/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js:34:15)
    at Module._compile (/opt/Tabby/resources/app.asar/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1324:10)
    at Module.load (node:internal/modules/cjs/loader:1124:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/opt/Tabby/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js',
    '/opt/Tabby/resources/app.asar/node_modules/node-pty/lib/index.js',
    '/opt/Tabby/resources/app.asar/dist/main.js',
    undefined
  ]
}
[118992:1117/144551.577287:ERROR:nss_util.cc(357)] After loading Root Certs, loaded==false: NSS error code: -8018
```

### PR DESCRIPTION
**Pull request by Clem-Fern**
Hey @Eugeny,

As describe in #9235, latest linux release is unusable. Sadly, I couldn't identify precisly where the problem was coming from.
I think it was related to node-gyp 10.0.0 dependecy in the root project. 0f6561e85922f38700cd328747a0ccacf4644274

I do not have any mac device with me. Could you try this build ? https://github.com/Eugeny/tabby/actions/runs/6883409733

There is also a weird behavior on the macos-12 runner image. The default python version for macos arm64 is python2 (python 3 on x86_64).
it does not seem to be an issue right now but it has to be kept in mind as this python version is now deprecated. It could bring some difficulty in the future.

Fix #9235
Fix #9242
Fix #9245

### CODE REVIEW

**Comment by Eugeny** [comment]
The build you linked works :+1:

**Comment by Clem-Fern** [comment]
I've got some graphic glitch with the title bar backgrond on windows 10 and 11 :/

**Comment by Eugeny** [comment]
Hmm... it looks fine on my windows 11 x64

**Comment by Clem-Fern** [comment]
Problem only appear when Settings > Window > Theme is set to `Follow the color scheme`

I can open a dedicated issue for this if you dont want to block this PR

**Comment by Eugeny** [comment]
Sure! You've already tested the linux builds, right?

**Comment by Clem-Fern** [comment]
> Sure! You've already tested the linux builds, right?

Yup, starting normally, but didn't get the time to dig in more in detail, sorry

**Comment by Upellift99** [comment]
> > Sure! You've already tested the linux builds, right?
> 
> Yup, starting normally, but didn't get the time to dig in more in detail, sorry

I've tested the Linux DEB amd64 build v1.0.205-nightly.0, and it's working again on Ubuntu 22.04 !

I've just noticed these small problems:
- the background of the drop-down menu in which you can choose the duration for saving the vault passphrase remains transparent;
- the value of the duration for saving the vault passphrase is not saved when you restart the app;
- the recent profiles are not saved when you restart the app.

But the rest of the application is completely usable!

Thank you!

**Comment by Clem-Fern** [comment]
@Upellift99 Thank's a lot for this feedback.

I wil try to fix this soon.

**Comment by Clem-Fern** [comment]
I wasnt able to reproduce any of theses issues :/

> - the background of the drop-down menu in which you can choose the duration for saving the vault passphrase remains transparent;
What theme do you use ?

> - the value of the duration for saving the vault passphrase is not saved when you restart the app;
> - the recent profiles are not saved when you restart the app.
Do you have any error in logs ?

A profile is pushed into recent profiles at tab opening and not on app shutdown. Restarting should not affect the recent profiles list.

Just after opening a profile, do you see it appears in recent list in Profiles & Connections ?

**Comment by Upellift99** [comment]
You are right, after rebooting the system, I can't reproduce all the problems, there is just the background of the drop-down menu which remains transparent. Sorry for that!
Capture d’écran du 2023-11-20 09-59-24
For the theme, you mean the color sheme? the name is _Expresso_

**Comment by Clem-Fern** [comment]
@Upellift99 no worry, thank you for the feedback anyway.

In that case, could you open an dedicated issue about this as it seems only to append with this color scheme.

**Comment by Upellift99** [comment]
Done! https://github.com/Eugeny/tabby/issues/9256

**Pull request merged**
