### PR TITLE
Add support for arm platforms

### LINKED ISSUE #3947: Support Linux ARM
I tried to install it on my Raspberry Pi. Unfortunately, the deb you provided only supports the amd64 architecture.

### PR DESCRIPTION
**Pull request by Jai-JAP**
Add support for 
  - Linux armv7l, arm64
  - Windows arm64
---
Closes #3947, #2694, #1492

### CODE REVIEW

**Comment by Eugeny** [comment]
Looking great, can't wait to test :+1:

**Comment by Jai-JAP** [comment]
Quick Status update:
Got Linux arm64 builds working

**Comment by Jai-JAP** [comment]
Quick Status update:
Got Windows arm64 builds working

**Comment by Jai-JAP** [comment]
Here are the build artifacts
https://github.com/Jai-JAP/tabby/actions/runs/1955581847

**Comment by Jai-JAP** [comment]
running armv7l gives the below log and hangs
```
innerError Error: Cannot find module '../build/Debug/pty.node'
Require stack:
- /opt/Tabby/resources/app.asar/node_modules/@tabby-gang/node-pty/lib/unixTerminal.js
- /opt/Tabby/resources/app.asar/node_modules/@tabby-gang/node-pty/lib/index.js
- /opt/Tabby/resources/app.asar/dist/main.js
- 
    at Module._resolveFilename (node:internal/modules/cjs/loader:940:15)
    at Function.n._resolveFilename (node:electron/js2c/browser_init:249:1105)
    at Module._load (node:internal/modules/cjs/loader:785:27)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (/opt/Tabby/resources/app.asar/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/opt/Tabby/resources/app.asar/node_modules/@tabby-gang/node-pty/lib/unixTerminal.js:33:15)
    at Module._compile (/opt/Tabby/resources/app.asar/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1169:10)
    at Module.load (node:internal/modules/cjs/loader:988:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/opt/Tabby/resources/app.asar/node_modules/@tabby-gang/node-pty/lib/unixTerminal.js',
    '/opt/Tabby/resources/app.asar/node_modules/@tabby-gang/node-pty/lib/index.js',
    '/opt/Tabby/resources/app.asar/dist/main.js',
    undefined
  ]
}
[28747:0309/123501.087413:ERROR:nss_util.cc(286)] After loading Root Certs, loaded==false: NSS error code: -8018
```

**Comment by Jai-JAP** [comment]
Windows arm64 is untested

**Comment by Eugeny** [comment]
That means that Node couldn't load the `app/node_modules/@tabby-gang/node-pty/build/Release/pty.node` native module, likely because it didn't get compiled for the correct arch. You can get the exact error by creating a `1.js` file in the repo root with the following content

```require('./app/node_modules/@tabby-gang/node-pty/build/Release/pty.node')```

and running it as `yarn electron 1.js`

**Comment by Jai-JAP** [comment]
The output of yarn electron 1.js
```
yarn run v1.19.1
$ /home/runner/work/tabby/tabby/node_modules/.bin/electron 1.js
/home/runner/work/tabby/tabby/node_modules/electron/dist/electron exited with signal SIGTRAP
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by Eugeny** [comment]
Looks like a native crash. Can you get a backtrace? Try

* `gdb /home/runner/work/tabby/tabby/node_modules/electron/dist/electron`
* `r 1.js`
* and, once it crashes, `bt`

**Comment by Jai-JAP** [comment]
> Looks like a native crash. Can you get a backtrace? Try
> 
>     * `gdb /home/runner/work/tabby/tabby/node_modules/electron/dist/electron`
> 
>     * `r 1.js`
> 
>     * and, once it crashes, `bt`

Currently i am away from my RPi to test arm 
I will try the above after i get to my RPi

**Comment by Jai-JAP** [comment]
Should work now as now node modules are rebuilt for arm
Will test tomorrow

**Comment by Jai-JAP** [comment]
modules are rebuilt but still doesn't work 
trying the backtrace now

**Comment by Jai-JAP** [comment]
unable to build due to issues on electron web page
Also looks like [this](https://github.com/yarnpkg/yarn/issues/2221#issuecomment-879783433) may solve the issue

**Comment by Jai-JAP** [comment]
> That means that Node couldn't load the `app/node_modules/@tabby-gang/node-pty/build/Release/pty.node` native module, likely because it didn't get compiled for the correct arch. You can get the exact error by creating a `1.js` file in the repo root with the following content
> 
> `require('./app/node_modules/@tabby-gang/node-pty/build/Release/pty.node')`
> 
> and running it as `yarn electron 1.js`
> 
> P.S. the module is built by `electron-rebuild` via `./scripts/build-native.js`

@Eugeny you are correct the module node-pty is built for x86_64, setting CC && CXX values to cross gcc gives out other build errors
You can check the status at 
https://github.com/Jai-JAP/tabby/tree/test

**Comment by Jai-JAP** [comment]
Also suggest fixes if you can catch any

**Comment by Eugeny** [comment]
Have you tried setting `process.env. npm_config_arch` in `build-linux.js`?

**Comment by Jai-JAP** [comment]
No but it is exported while running workflows as here https://github.com/jai-jap/tabby/blob/test/.github/workflows/build.yml#L202

**Comment by Eugeny** [comment]
And it's still getting built for x86_64?!

**Comment by Jai-JAP** [comment]
> And it's still getting built for x86_64?!

Yes even after add ing the npm_config_arch to build-linux.js

Maybe the issue is CC & CXX variables not being forwarded to node-gyp but I don't know how tofix that

**Comment by Eugeny** [comment]
Could something like this work? https://github.com/pguyot/arm-runner-action

**Comment by Jai-JAP** [comment]
No thats not gonna work as it is used to create custom images for RPi
I already had a look on that action seeing a hope for this project

**Comment by Eugeny** [comment]
This guy is setting a fair few more tool names: http://www.qinuu.com/2018/05/10/cross-compile-with-node-js-c-addons-to-arm/

**Comment by Jai-JAP** [comment]
> Maybe the issue is CC & CXX variables not being forwarded to node-gyp but I don't know how to fix that
@Eugeny any ideas??

Also similar issue is being worked on in hyper terminal [here](https://github.com/vercel/hyper/pull/6370) it also has same issues with node-pty

**Comment by Jai-JAP** [comment]
> This guy is setting a fair few more tool names: http://www.qinuu.com/2018/05/10/cross-compile-with-node-js-c-addons-to-arm/
> 
> > **[Cross compile with Node.js C++ Addons to ARM – Water's Home](http://www.qinuu.com/2018/05/10/cross-compile-with-node-js-c-addons-to-arm/)**

But in current state possibly no env vars are passed to node-gyp

**Comment by Jai-JAP** [comment]
https://github.com/oznu/node-pty-prebuilt-multiarch
maybe this will work

**Comment by Jai-JAP** [comment]
As instructed from [here](https://github.com/nodejs/node-gyp/issues/829#issuecomment-665527032) i tried cross building 
But its failing at 
```
error /home/runner/work/tabby/tabby/app/node_modules/native-process-working-directory: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments: 
Directory: /home/runner/work/tabby/tabby/app/node_modules/native-process-working-directory
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@8.4.1
gyp info using node@16.14.0 | linux | x64
gyp info find Python using Python version 3.6.9 found at "/usr/bin/python3"
gyp http GET https://nodejs.org/download/release/v16.14.0/node-v16.14.0-headers.tar.gz
gyp http 200 https://nodejs.org/download/release/v16.14.0/node-v16.14.0-headers.tar.gz
gyp http GET https://nodejs.org/download/release/v16.14.0/SHASUMS256.txt
gyp http 200 https://nodejs.org/download/release/v16.14.0/SHASUMS256.txt
gyp info spawn /usr/bin/python3
gyp info spawn args [
gyp info spawn args   '/opt/hostedtoolcache/node/16.14.0/x64/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/runner/work/tabby/tabby/app/node_modules/native-process-working-directory/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/opt/hostedtoolcache/node/16.14.0/x64/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/runner/.cache/node-gyp/16.14.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/runner/.cache/node-gyp/16.14.0',
gyp info spawn args   '-Dnode_gyp_dir=/opt/hostedtoolcache/node/16.14.0/x64/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/runner/.cache/node-gyp/16.14.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/runner/work/tabby/tabby/app/node_modules/native-process-working-directory',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/home/runner/work/tabby/tabby/app/node_modules/native-process-working-directory/build'
  SOLINK_MODULE(target) Release/obj.target/native-process-working-directory.node
aarch64-linux-gnu-g++: error: unrecognized command line option ‘-m64’
native-process-working-directory.target.mk:22: recipe for target 'Release/obj.target/native-process-working-directory.node' failed
make: *** [Release/obj.target/native-process-working-directory.node] Error 1
make: Leaving directory '/home/runner/work/tabby/tabby/app/node_modules/native-process-working-directory/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/opt/hostedtoolcache/node/16.14.0/x64/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (node:events:520:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
gyp ERR! System Linux 5.4.0-1070-azure
gyp ERR! command "/opt/hostedtoolcache/node/16.14.0/x64/bin/node" "/opt/hostedtoolcache/node/16.14.0/x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/runner/work/tabby/tabby/app/node_modules/native-process-working-directory
gyp ERR! node -v v16.14.0
gyp ERR! node-gyp -v v8.4.1
gyp ERR! not ok
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Error: Process completed with exit code 1.
```

**Comment by Jai-JAP** [comment]
For now i will close this pr and reopen when ready to merge as it is far from completion for cross-compile to work
Also i suggest you to remove Mac OS arm builds if they aren't tested as they may also face the same issue as cross-compiling doesn't work well for node-pty

**Comment by Jai-JAP** [comment]
> As instructed from [here](https://github.com/nodejs/node-gyp/issues/829#issuecomment-665527032) i tried cross building But its failing at
> 
> ```
> error /home/runner/work/tabby/tabby/app/node_modules/native-process-working-directory: Command failed.
> Exit code: 1
> Command: node-gyp rebuild
> Arguments: 
> Directory: /home/runner/work/tabby/tabby/app/node_modules/native-process-working-directory
> Output:
> gyp info it worked if it ends with ok
> gyp info using node-gyp@8.4.1
> gyp info using node@16.14.0 | linux | x64
> gyp info find Python using Python version 3.6.9 found at "/usr/bin/python3"
> gyp http GET https://nodejs.org/download/release/v16.14.0/node-v16.14.0-headers.tar.gz
> gyp http 200 https://nodejs.org/download/release/v16.14.0/node-v16.14.0-headers.tar.gz
> gyp http GET https://nodejs.org/download/release/v16.14.0/SHASUMS256.txt
> gyp http 200 https://nodejs.org/download/release/v16.14.0/SHASUMS256.txt
> gyp info spawn /usr/bin/python3
> gyp info spawn args [
> gyp info spawn args   '/opt/hostedtoolcache/node/16.14.0/x64/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
> gyp info spawn args   'binding.gyp',
> gyp info spawn args   '-f',
> gyp info spawn args   'make',
> gyp info spawn args   '-I',
> gyp info spawn args   '/home/runner/work/tabby/tabby/app/node_modules/native-process-working-directory/build/config.gypi',
> gyp info spawn args   '-I',
> gyp info spawn args   '/opt/hostedtoolcache/node/16.14.0/x64/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
> gyp info spawn args   '-I',
> gyp info spawn args   '/home/runner/.cache/node-gyp/16.14.0/include/node/common.gypi',
> gyp info spawn args   '-Dlibrary=shared_library',
> gyp info spawn args   '-Dvisibility=default',
> gyp info spawn args   '-Dnode_root_dir=/home/runner/.cache/node-gyp/16.14.0',
> gyp info spawn args   '-Dnode_gyp_dir=/opt/hostedtoolcache/node/16.14.0/x64/lib/node_modules/npm/node_modules/node-gyp',
> gyp info spawn args   '-Dnode_lib_file=/home/runner/.cache/node-gyp/16.14.0/<(target_arch)/node.lib',
> gyp info spawn args   '-Dmodule_root_dir=/home/runner/work/tabby/tabby/app/node_modules/native-process-working-directory',
> gyp info spawn args   '-Dnode_engine=v8',
> gyp info spawn args   '--depth=.',
> gyp info spawn args   '--no-parallel',
> gyp info spawn args   '--generator-output',
> gyp info spawn args   'build',
> gyp info spawn args   '-Goutput_dir=.'
> gyp info spawn args ]
> gyp info spawn make
> gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
> make: Entering directory '/home/runner/work/tabby/tabby/app/node_modules/native-process-working-directory/build'
>   SOLINK_MODULE(target) Release/obj.target/native-process-working-directory.node
> aarch64-linux-gnu-g++: error: unrecognized command line option ‘-m64’
> native-process-working-directory.target.mk:22: recipe for target 'Release/obj.target/native-process-working-directory.node' failed
> make: *** [Release/obj.target/native-process-working-directory.node] Error 1
> make: Leaving directory '/home/runner/work/tabby/tabby/app/node_modules/native-process-working-directory/build'
> gyp ERR! build error 
> gyp ERR! stack Error: `make` failed with exit code: 2
> gyp ERR! stack     at ChildProcess.onExit (/opt/hostedtoolcache/node/16.14.0/x64/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
> gyp ERR! stack     at ChildProcess.emit (node:events:520:28)
> gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
> gyp ERR! System Linux 5.4.0-1070-azure
> gyp ERR! command "/opt/hostedtoolcache/node/16.14.0/x64/bin/node" "/opt/hostedtoolcache/node/16.14.0/x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
> gyp ERR! cwd /home/runner/work/tabby/tabby/app/node_modules/native-process-working-directory
> gyp ERR! node -v v16.14.0
> gyp ERR! node-gyp -v v8.4.1
> gyp ERR! not ok
> info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
> Error: Process completed with exit code 1.
> ```

This error is occuring also for arm native compiling so maybe some errors in the code itself

**Comment by Jai-JAP** [comment]
Got a successful arm64 build natively on a pi4
but for armv7l this may not be possible as 
```
Building against Electron 17.1.2
Rebuilding app/bindings-cpp
Rebuilding app/node-pty
make: Entering directory '/home/pi/tabby/app/node_modules/@tabby-gang/node-pty/build'
  CXX(target) Release/obj.target/pty/src/unix/pty.o
In file included from /home/pi/.electron-gyp/17.1.2/include/node/v8-local-handle.h:12,
                 from /home/pi/.electron-gyp/17.1.2/include/node/v8-array-buffer.h:12,
                 from /home/pi/.electron-gyp/17.1.2/include/node/v8.h:25,
                 from /home/pi/.electron-gyp/17.1.2/include/node/node.h:63,
                 from ../../../nan/nan.h:56,
                 from ../src/unix/pty.cc:20:
/home/pi/.electron-gyp/17.1.2/include/node/v8-internal.h:113:27: error: static assertion failed: Pointer compression can be enabled only for 64-bit architectures
     kApiSystemPointerSize == kApiInt64Size,
     ~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~
/home/pi/.electron-gyp/17.1.2/include/node/v8-internal.h:471:71: warning: left shift count >= width of type [-Wshift-count-overflow]
   static constexpr size_t kPtrComprCageReservationSize = size_t{1} << 32;
                                                                       ^~
/home/pi/.electron-gyp/17.1.2/include/node/v8-internal.h:471:68: error: right operand of shift expression ‘(1 << 32)’ is >= than the precision of the left operand [-fpermissive]
   static constexpr size_t kPtrComprCageReservationSize = size_t{1} << 32;
                                                          ~~~~~~~~~~^~~~~
/home/pi/.electron-gyp/17.1.2/include/node/v8-internal.h:472:69: warning: left shift count >= width of type [-Wshift-count-overflow]
   static constexpr size_t kPtrComprCageBaseAlignment = size_t{1} << 32;
                                                                     ^~
/home/pi/.electron-gyp/17.1.2/include/node/v8-internal.h:472:66: error: right operand of shift expression ‘(1 << 32)’ is >= than the precision of the left operand [-fpermissive]
   static constexpr size_t kPtrComprCageBaseAlignment = size_t{1} << 32;
                                                        ~~~~~~~~~~^~~~~
/home/pi/.electron-gyp/17.1.2/include/node/v8-internal.h:509:48: warning: conversion from ‘long long unsigned int’ to ‘size_t’ {aka ‘unsigned int’} changes value from ‘1099511627776’ to ‘0’ [-Woverflow]
 constexpr size_t kVirtualMemoryCageSize = 1ULL << kVirtualMemoryCageSizeLog2;
                                           ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/pi/.electron-gyp/17.1.2/include/node/v8-internal.h:528:60: warning: conversion from ‘long long unsigned int’ to ‘size_t’ {aka ‘unsigned int’} changes value from ‘34359738368’ to ‘0’ [-Woverflow]
 constexpr size_t kVirtualMemoryCageGuardRegionSize = 32ULL * GB;
                                                            ^
/home/pi/.electron-gyp/17.1.2/include/node/v8-internal.h:542:56: warning: conversion from ‘long long unsigned int’ to ‘size_t’ {aka ‘unsigned int’} changes value from ‘34359738368’ to ‘0’ [-Woverflow]
 constexpr size_t kVirtualMemoryCageMinimumSize = 32ULL * GB;
                                                        ^
/home/pi/.electron-gyp/17.1.2/include/node/v8-internal.h:557:66: warning: conversion from ‘long long unsigned int’ to ‘size_t’ {aka ‘unsigned int’} changes value from ‘8589934592’ to ‘0’ [-Woverflow]
 constexpr size_t kFakeVirtualMemoryCageMinReservationSize = 8ULL * GB;
                                                                  ^
In file included from /home/pi/.electron-gyp/17.1.2/include/node/v8.h:53,
                 from /home/pi/.electron-gyp/17.1.2/include/node/node.h:63,
                 from ../../../nan/nan.h:56,
                 from ../src/unix/pty.cc:20:
/home/pi/.electron-gyp/17.1.2/include/node/v8-script.h:232:79: warning: ‘ResolveCallback’ is deprecated [-Wdeprecated-declarations]
                                                      ResolveCallback callback);
                                                                              ^

../src/unix/pty.cc: In function ‘void pty_after_waitpid(uv_async_t*)’:
../src/unix/pty.cc:536:43: warning: ‘void* memset(void*, int, size_t)’ writing to an object of type ‘class Nan::Persistent<v8::Function>’ with no trivial copy-assignment [-Wclass-memaccess]
   memset(&baton->cb, -1, sizeof(baton->cb));
                                           ^
In file included from ../../../nan/nan.h:405,
                 from ../src/unix/pty.cc:20:
../../../nan/nan_persistent_12_inl.h:12:40: note: ‘class Nan::Persistent<v8::Function>’ declared here
 template<typename T, typename M> class Persistent :
                                        ^~~~~~~~~~
In file included from ../../../nan/nan.h:56,
                 from ../src/unix/pty.cc:20:
../src/unix/pty.cc: At global scope:
/home/pi/.electron-gyp/17.1.2/include/node/node.h:832:43: warning: cast between incompatible function types from ‘void (*)(Nan::ADDON_REGISTER_FUNCTION_ARGS_TYPE)’ {aka ‘void (*)(v8::Local<v8::Object>)’} to ‘node::addon_register_func’ {aka ‘void (*)(v8::Local<v8::Object>, v8::Local<v8::Value>, void*)’} [-Wcast-function-type]
       (node::addon_register_func) (regfunc),                          \
                                           ^
/home/pi/.electron-gyp/17.1.2/include/node/node.h:866:3: note: in expansion of macro ‘NODE_MODULE_X’
   NODE_MODULE_X(modname, regfunc, NULL, 0)  // NOLINT (readability/null_usage)
   ^~~~~~~~~~~~~
../src/unix/pty.cc:709:1: note: in expansion of macro ‘NODE_MODULE’
 NODE_MODULE(pty, init)
 ^~~~~~~~~~~
make: *** [pty.target.mk:123: Release/obj.target/pty/src/unix/pty.o] Error 1
make: Leaving directory '/home/pi/tabby/app/node_modules/@tabby-gang/node-pty/build'
Error: node-gyp failed to rebuild '/home/pi/tabby/app/node_modules/@tabby-gang/node-pty'.
For more information, rerun with the DEBUG environment variable set to "electron-rebuild".

Error: `make` failed with exit code: 2


    at NodeGyp.rebuildModule (/home/pi/tabby/node_modules/electron-rebuild/lib/src/module-type/node-gyp.js:117:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ModuleRebuilder.rebuildNodeGypModule (/home/pi/tabby/node_modules/electron-rebuild/lib/src/module-rebuilder.js:94:9)
    at async ModuleRebuilder.rebuild (/home/pi/tabby/node_modules/electron-rebuild/lib/src/module-rebuilder.js:124:14)
    at async Rebuilder.rebuildModuleAt (/home/pi/tabby/node_modules/electron-rebuild/lib/src/rebuild.js:145:13)
    at async Rebuilder.rebuild (/home/pi/tabby/node_modules/electron-rebuild/lib/src/rebuild.js:108:17)
```
says that 
```
n file included from /home/pi/.electron-gyp/17.1.2/include/node/v8-local-handle.h:12,
                 from /home/pi/.electron-gyp/17.1.2/include/node/v8-array-buffer.h:12,
                 from /home/pi/.electron-gyp/17.1.2/include/node/v8.h:25,
                 from /home/pi/.electron-gyp/17.1.2/include/node/node.h:63,
                 from ../../../nan/nan.h:56,
                 from ../src/unix/pty.cc:20:
/home/pi/.electron-gyp/17.1.2/include/node/v8-internal.h:113:27: error: static assertion failed: Pointer compression can be enabled only for 64-bit architectures
```
implying 32 bit builds are not possible and also has many other errors

**Comment by Eugeny** [comment]
You're right, looks like Electron just doesn't support 32-bit anymore.

**Comment by Jai-JAP** [comment]
Tried another approach for cross build using chroot but i am unsuccessful.
See https://github.com/Jai-JAP/tabby/actions/runs/2015797408

**Comment by Jai-JAP** [comment]
by downgrading electron to 17.0.0 I was able to go a bit further with armv7l build of tabby v1.0.173 but still it finally fails at `scripts/build-linux.js` giving out
```
/home/pi/tabby/node_modules/builder-util/src/arch.ts:48
      throw new Error(`Unsupported arch ${name}`)
            ^
Error: Unsupported arch arm
    at Object.archFromString (/home/pi/tabby/node_modules/builder-util/src/arch.ts:48:13)
    at commonArch (/home/pi/tabby/node_modules/electron-builder/src/builder.ts:52:62)
    at processTargets (/home/pi/tabby/node_modules/electron-builder/src/builder.ts:74:28)
    at normalizeOptions (/home/pi/tabby/node_modules/electron-builder/src/builder.ts:86:5)
    at build (/home/pi/tabby/node_modules/electron-builder/src/builder.ts:211:24)
    at Object.<anonymous> (/home/pi/tabby/scripts/build-linux.js:7:1)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1155:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47
```

which makes it obvious that arm builds are not supported by one or more of other modules required by tabby

**Comment by theofficialgman** [comment]
> builder-util/src/arch.ts

@Jai-JAP I think you are passing it the wrong name, its not `arm` its `armv7l`
from `builder-util/src/arch.ts`
```
export enum Arch {
  ia32,
  x64,
  armv7l,
  arm64,
  universal,
}

export type ArchType = "x64" | "ia32" | "armv7l" | "arm64" | "universal"

export function toLinuxArchString(arch: Arch, targetName: string): string {
  switch (arch) {
    case Arch.x64:
      return targetName === "flatpak" ? "x86_64" : "amd64"
    case Arch.ia32:
      return targetName === "pacman" ? "i686" : "i386"
    case Arch.armv7l:
      return targetName === "snap" || targetName === "deb" ? "armhf" : targetName === "flatpak" ? "arm" : "armv7l"
    case Arch.arm64:
      return targetName === "pacman" || targetName === "flatpak" ? "aarch64" : "arm64"

    default:
      throw new Error(`Unsupported arch ${arch}`)
  }
}```

**Comment by Jai-JAP** [comment]
arm is the arch name grabbed automatically by the scripts on a pi4 armhf & setting it to armv7l makes no difference

**Comment by theofficialgman** [comment]
> arm is the arch name grabbed automatically by the scripts on a pi4 armhf & setting it to armv7l makes no difference

where are you setting this? are you setting it within the electron-builder build-linux.js locally https://github.com/Jai-JAP/tabby/blob/master/scripts/build-linux.js? https://www.electron.build/cli.html

if you can't figure it out, maybe @SpacingBat3 could lend some assistance with the github actions and the scripts

**Comment by SpacingBat3** [comment]
Using Electron Builder with ARM is a terrible experience – it is just not prepared for it and most distribution-specific distributables might just fail to build. My advice is to use Electron Forge instead.

Anyway, from what I believe Electron Builder *supports* `armv7l` as the valid architecture, however `arm` is the one returned by Node.js, as it is mentioned [in the documentation](https://nodejs.org/api/process.html#processarch). There're however command line parameters for Electron Builder to enforce creating a distributable for specific platform / architecture.

**Comment by Jai-JAP** [comment]
Hooray!!!
Just got the first amhf (armv7l) build working there was an error setting arch name as armv7l instead of arm
just adding `    armv7l: process.arch === 'arm' || process.arch ==='armv7l',` after the line 
`    linux: ['deb', 'tar.gz', 'rpm', 'pacman'],` made it work flawlwssly on electron 17.0.0

**Comment by Jai-JAP** [comment]
still crossbuilding issue persists
I think that we should enable armv7l and arm64 in scripts/build-linux.js but leave it for the ci to not compile arm versions in an other PR
What do you think @Eugeny

**Comment by Eugeny** [comment]
Does this mean that x64->arm crossbuild doesn't work at all? Then we should lock it behind `process.arch` check.

**Comment by Jai-JAP** [comment]
> Does this mean that x64->arm crossbuild doesn't work at all? Then we should lock it behind `process.arch` check.

yes I am suggesting this because after this it will build for linux arm64 if only on such host no messy crosscompiling

**Comment by Jai-JAP** [comment]
Updating soon

**Comment by Jai-JAP** [comment]
Windows arm64 builds are confirmed working

**Comment by Jai-JAP** [comment]
Linux arm builds compiled by me on a RPi4 are located at https://github.com/jai-jap/tabby-arm-builds/releases
Confirmed working

**Comment by Jai-JAP** [comment]
Build artifacts for the latest commit can be found [here](https://github.com/Jai-JAP/tabby/actions/runs/2040346796)

Windows arm64 portable is known working but the installer should also work as building arm64 is supported natively on Windows and Mac OS by electron

**Comment by Jai-JAP** [comment]
This is now ready to merge in my view
@Eugeny have a look

**Comment by theofficialgman** [comment]
I don't see why the electron downgrade is necessary.
When I look at the electron releases on the github https://github.com/electron/electron/releases/tag/v17.2.0, prebuilts for ia32 (x86), x64 (x86_64), armv7l, and arm64 are all there

**Comment by Jai-JAP** [comment]
> Fantastic 👍
> 
> Is the `electron==17.0.0` downgrade still necessary on Linux?

Yes since for electron >= 17.0.1 compiling v8 engine results in error same as in [this](https://github.com/Eugeny/tabby/pull/5907#issuecomment-1073604638) comment

**Comment by Eugeny** [comment]
Got it - fantastic work! 

@allcontributors please add @Jai-JAP for platfomr

**Comment by Eugeny** [comment]
@allcontributors please add @Jai-JAP for platform

**Comment by Eugeny** [comment]
@Jai-JAP the PR accidentally broke x86_64 Windows builds - I've fixed it in 95ae4b84a60f998ff0a764169d43ffc577e38e3e but could you please double-check that the arm64 build is still working after this?

**Comment by Jai-JAP** [comment]
I 2ill check this later as i am busy with exams

**Comment by Jai-JAP** [comment]
> @Jai-JAP the PR accidentally broke x86_64 Windows builds - I've fixed it in [95ae4b8](https://github.com/Eugeny/tabby/commit/95ae4b84a60f998ff0a764169d43ffc577e38e3e) but could you please double-check that the arm64 build is still working after this?

No they don't as Windows arm64 build artifacts are the x64 builds with other name and not arm64 ones

**Comment by Jai-JAP** [comment]
https://github.com/Eugeny/tabby/blob/95ae4b84a60f998ff0a764169d43ffc577e38e3e/scripts/build-native.js#L6
the ?? in this line seems to be the issue. I think it should be ||
Also the brackets may be the issue too

**Comment by Jai-JAP** [comment]
Probably fixed #6106

**Comment by mirogl** [comment]
Hi,
I tested release 1.0.176 Windows arm64 portable. Just unpacked it and created an empty data dir in the new directory.
When i start Tabby.exe from cmd i get 👍 

C:\Users\miros\Downloads\tabby>
reset user data to C:\Users\miros\Downloads\tabby\data
[27940:0421/101508.583:ERROR:gpu_init.cc(446)] Passthrough is not supported, GL is disabled, ANGLE is

But i don't get any Window.

I habe a Surface Pro X with SQ2 Arm64 processor and Windows 11 Version 10.0.22000 Build 22000

Thanks
Miro

**Comment by Jai-JAP** [comment]
Can you try adding `--disable-gpu` to i.e., args run the command `Tabby.exe --disable-gpu`

**Comment by Jai-JAP** [comment]
Also if it doesn't work delete all tabby folders in %APPDATA% and also in downloads and try again

**Comment by Jai-JAP** [comment]
@Eugeny this is not related to tabby and is likely an issue with electron/chromium itself. See https://github.com/electron/electron/issues/32317

**Comment by mirogl** [comment]
> Also if it doesn't work delete all tabby folders in %APPDATA% and also in downloads and try again

Hi,thanks - i deleted %APPDATTA%\tabby and the existing Folder under Downloads. After a Reboot i unpacked tabby-1.0.176-portable-arm64.zip and created a emoty data direcoty in the extracted dir.

Still hangs at:

C:\Users\miros\Downloads\tabby-1.0.176-portable-arm64>
reset user data to C:\Users\miros\Downloads\tabby-1.0.176-portable-arm64\data

Cheers 
Miro

**Comment by Jai-JAP** [comment]
@mirogl can you open a new issue with all details

**Pull request merged**
