### PR TITLE
Improving tabby startup time

### PR DESCRIPTION
**Pull request by Clem-Fern**
Hi @Eugeny,

I found some issues about how tabby can be slow to launch in some case (#6295 , #7390 , #6253 ).
After taking a quick look, I saw that installed plugins are loaded one after another at the app startup. 

This PR aim to improve the startup time by finding and loading the plugins simultaneously.

Startup on latest release with 0 plugins : ~2.9sec
Startup on latest release with 8 plugins : ~3.5sec

Startup on this PR with 0 plugins : ~2.3sec
Startup on this PR with 8 plugins : ~2.3sec

I've only have SSD so there is no huge gab on my side. (Tested on Debian 11, don't have other system on hand sorry :/)

As always, I am not sure theses changes are really relevant nor if it is a good approach to try to reduce the startup time. I hope you could give me a feedback on this when you got time :D

### CODE REVIEW

**Comment by Eugeny** [comment]
I've tested it and it improves my startup time from 2.7s to 2.1s, great work!

**Comment by Clem-Fern** [comment]
Good to hear that !

**Comment by Clem-Fern** [comment]
Well, I took another look in it to be sure I had done everything I could. But I think we're good for this time.

I've just added a new commit to fix a mistake I've made in the placement of the call of the progress bar.

**Comment by Eugeny** [comment]
Perfect 👌

**Pull request merged**
